"""
" service name
"""
MOTION_SWITCHER_SERVICE_NAME = "motion_switcher"


"""
" service api version
"""
MOTION_SWITCHER_API_VERSION = "1.0.0.1"


"""
" api id
"""
MOTION_SWITCHER_API_ID_GET_MODE = 1001
MOTION_SWITCHER_API_ID_SET_MODE = 1002
MOTION_SWITCHER_API_ID_RELEASE_MODE = 1003
MOTION_SWITCHER_API_ID_SET_SILENT = 1004
MOTION_SWITCHER_API_ID_GET_SILENT = 1005

